[project]
name = 'Virtual-World-Governance-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.avatar]
path = 'contracts/avatar.clar'
clarity_version = 2
epoch = 2.5

[contracts.economy]
path = 'contracts/economy.clar'
clarity_version = 2
epoch = 2.5

[contracts.land-management]
path = 'contracts/land-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
